name: PruebaSurge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Surge
        run: npm install -g surge@latest

      - name: Ver versión
        run: surge --version

      - name: Mostrar contenido
        run: |
          pwd
          ls -la
          cat index.html

      - name: Deploy a Surge
        run: surge $GITHUB_WORKSPACE jeremy20242517.surge.sh  --token ${{ secrets.SURGE_TOKEN }}